module.exports = {
  SET_USER: "SET_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SET_TOKEN: "SET_TOKEN",
  SET_CURRENT_ITEM: "SET_CURRENT_ITEM",
  UPDATE_USER_PIC: "UPDATE_USER_PIC",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  SET_CURRENT_ORDER: "SET_CURRENT_ORDER",
  SET_SELECTED_SALESMAN: "SET_SELECTED_SALESMAN",
};
